<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/fontawesome.min.css">
<link rel="stylesheet" href="/assets/css/prettify.css">
<link rel="stylesheet" href="/assets/js/markitup/style.css">
<link rel="stylesheet" href="/assets/css/toastr.min.css">
<link rel="stylesheet" href="/assets/js/mediaelement/mediaelementplayer.min.css">
<link rel="stylesheet" href="/assets/js/mediaelement/mejs-skins.css">
<link rel="stylesheet" href="/assets/js/colorbox/colorbox.css">
<link rel="stylesheet" href="/assets/css/app.css">
