#!/usr/bin/env php
<?php
require __DIR__.'/app/bootstrap.php';

$app = new Phinx\Console\PhinxApplication();
$app->setName('RotorCMS by Vantuz - http://visavi.net');
$app->setVersion(VERSION);

$app->addCommands([
    new \App\Commands\Install(),
    new \App\Commands\KeyGenerate(),
]);

$app->run();
