#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Phinx\Console\PhinxApplication;
use Phinx\Console\Command;

require __DIR__.'/app/bootstrap.php';

/*class RotorApplication extends PhinxApplication
{
    public function doRun(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('<info>RotorCMS by Vantuz - http://visavi.net.</info> version <comment>'.VERSION.'</comment>');
        parent::doRun($input, $output);
    }
}

//class RotorCommand



$app = new RotorApplication();*/

$app = require __DIR__.'/vendor/robmorgan/phinx/app/phinx.php';
$app->setName('RotorCMS by Vantuz - http://visavi.net');
$app->setVersion(VERSION);

$app->addCommands(array(
    new Command\SeedRun("migration:seed-run2"),
));
$app->run();
