<?php

use Granada\Granada;
use \Granada\Orm\Wrapper;

/**
 * @method static Wrapper create($data=null)
 * @method static Wrapper non_associative()
 * @method static Wrapper associative()
 * @method static Wrapper reset_associative()
 * @method static Wrapper use_id_column($id_column)
 * @method static Wrapper find_one($id=null)
 * @method static Wrapper find_many()
 * @method static Wrapper find_result_set()
 * @method static Wrapper find_array()
 * @method static Wrapper count($column = '*')
 * @method static Wrapper max($column)
 * @method static Wrapper min($column)
 * @method static Wrapper avg($column)
 * @method static Wrapper sum($column)
 * @method static Wrapper force_all_dirty()
 * @method static Wrapper raw_query($query, $parameters = [])
 * @method static Wrapper table_alias($alias)
 * @method static Wrapper select($column, $alias=null)
 * @method static Wrapper select_expr($expr, $alias=null)
 * @method static Wrapper select_many()
 * @method static Wrapper select_many_expr()
 * @method static Wrapper join($table, $constraint, $table_alias=null)
 * @method static Wrapper inner_join($table, $constraint, $table_alias=null)
 * @method static Wrapper left_outer_join($table, $constraint, $table_alias=null)
 * @method static Wrapper right_outer_join($table, $constraint, $table_alias=null)
 * @method static Wrapper full_outer_join($table, $constraint, $table_alias=null)
 * @method static Wrapper where($column_name, $value)
 * @method static Wrapper where_equal($column_name, $value)
 * @method static Wrapper where_not_equal($column_name, $value)
 * @method static Wrapper where_id_is($id)
 * @method static Wrapper where_any_is($values, $operator='=')
 * @method static Wrapper where_like($column_name, $value)
 * @method static Wrapper where_not_like($column_name, $value)
 * @method static Wrapper where_gt($column_name, $value)
 * @method static Wrapper where_lt($column_name, $value)
 * @method static Wrapper where_gte($column_name, $value)
 * @method static Wrapper where_lte($column_name, $value)
 * @method static Wrapper where_in($column_name, $values)
 * @method static Wrapper where_not_in($column_name, $values)
 * @method static Wrapper where_null($column_name)
 * @method static Wrapper where_not_null($column_name)
 * @method static Wrapper where_raw($clause, $parameters=array())
 * @method static Wrapper limit($limit)
 * @method static Wrapper offset($offset)
 * @method static Wrapper order_by_desc($column_name)
 * @method static Wrapper order_by_asc($column_name)
 * @method static Wrapper order_by_expr($clause)
 * @method static Wrapper group_by($column_name)
 * @method static Wrapper group_by_expr($expr)
 * @method Wrapper having($column_name, $value)
 * @method Wrapper having_equal($column_name, $value)
 * @method Wrapper having_not_equal($column_name, $value)
 * @method Wrapper having_id_is($id)
 * @method Wrapper having_like($column_name, $value)
 * @method Wrapper having_not_like($column_name, $value)
 * @method Wrapper having_gt($column_name, $value)
 * @method Wrapper having_lt($column_name, $value)
 * @method Wrapper having_gte($column_name, $value)
 * @method Wrapper having_lte($column_name, $value)
 * @method Wrapper having_in($column_name, $values)
 * @method Wrapper having_not_in($column_name, $values)
 * @method Wrapper having_null($column_name)
 * @method Wrapper having_not_null($column_name)
 * @method Wrapper having_raw($clause, $parameters=array())
 * @method Wrapper hydrate($data=array())
 * @method Wrapper as_array()
 * @method Wrapper get($key)
 * @method Wrapper id()
 * @method Wrapper set($key, $value = null)
 * @method Wrapper set_expr($key, $value = null)
 * @method Wrapper is_dirty($key)
 * @method Wrapper list_dirty_fields()
 * @method Wrapper is_new()
 * @method Wrapper save($ignore = false)
 * @method Wrapper delete()
 * @method static Wrapper delete_many($join = false, $table = false)
 *
 * @mixin Wrapper|\Granada\ORM
 */
class BaseModel extends Granada {

}
