import '../sass/app.scss';
import 'js/jquery.js';
import 'jquery-mask-plugin';
import 'bootstrap';
import 'js/globals.js';
import 'js/translate.js';
import 'js/tiptap-editor.js';
import 'js/prettify.js';
import 'js/main.js';
