name: Build release
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Move .env file
        run: mv .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-dev -o --prefer-dist --ignore-platform-reqs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and run production scripts
        run: npm run prod

      - name: Remove node_modules
        run: rm -r node_modules

      - name: Clear vendor
        run: php vendor/bin/cleanup

      - name: Create Archive
        run: zip -r archive.zip .

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: composer-archive
          path: archive.zip
